main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('projects/', views.projects_index, name='index'),
    path('accounts/signup/', views.signup, name='signup'),
    path('projects/<int:project_id>/', views.projects_detail, name='detail'),
    path('projects/create/', views.ProjectCreate.as_view(), name='projects_create'),
    path('projects/<int:pk>/update/', views.ProjectUpdate.as_view(), name='projects_update'),
    path('projects/<int:pk>/delete/', views.ProjectDelete.as_view(), name='projects_delete'),
    path('projects/<int:project_id>/add_comment/', views.add_comment, name='add_comment'),
    path('projects/<int:project_id>/<int:task_id>/', views.tasks_detail, name='tasks_detail'),
    path('projects/<int:project_id>/tasks_create/', views.TaskCreate.as_view(), name='tasks_create'),
    path('projects/<int:project_id>/<int:pk>/tasks_update/', views.TaskUpdate.as_view(), name='tasks_update'),
    path('projects/<int:project_id>/<int:pk>/tasks_delete/', views.TaskDelete.as_view(), name='tasks_delete'),
    path('projects/<int:project_id>/assoc_member/<int:member_id>', views.assoc_member, name='assoc_member'),
    path('projects/<int:project_id>/unassoc_member/<int:member_id>', views.unassoc_member, name='unassoc_member'),
]

workflowwiz/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User

PRIORITIES = (
    ('H', 'High'),
    ('M', 'Medium'),
    ('L', 'Low'),
)

class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    completion = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='main_user')
    members = models.ManyToManyField(User, related_name='project_members')
    
    def __str__(self):
        return f'({self.title} {self.id})'
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={'project_id': self.id})
    

class Task(models.Model):
    title = models.CharField(max_length=100)
    assignee = models.CharField(max_length=50)
    description = models.TextField(max_length=250)
    due_date = models.DateField('Due Date')
    completion = models.BooleanField(default=False)
    priority = models.CharField(
        max_length=1,
        choices=PRIORITIES,
        default=PRIORITIES[0][0]
    )

    project = models.ForeignKey(
        Project, 
        on_delete=models.CASCADE
    )

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={'project_id': self.project_id}) 
    
class Comment(models.Model):
    comment = models.TextField(max_length=250)
    user = models.ForeignKey( User, on_delete=models.CASCADE)
    project = models.ForeignKey( Project, on_delete=models.CASCADE)


    class Meta:
        ordering = ['id']

main_app/forms.py
from django import forms
from django.forms import ModelForm
from django.forms.widgets import TextInput, Textarea
from .models import Comment, Task, Project

class DateInput(forms.DateInput):
    input_type = 'date'

class CommentForm(ModelForm):
  class Meta:
    model = Comment
    fields = ['comment']
    widgets = {
            'comment': forms.Textarea(attrs={
                'style':'width: 95%; height: 50px; border-radius: 10px; border: solid 1px #ee6c4d;'})
        }


class TaskForm(ModelForm):

    class Meta:
        model = Task
        fields = ['title', 'assignee', 'description', 'due_date', 'priority', 'completion']
        widgets = {
            'title': TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter task title'}),
            'assignee': TextInput(attrs={'class': 'form-control', 'placeholder': 'Assignee'}),
            'description': Textarea(attrs={'class': 'form-control', 'placeholder': 'Enter task description'}),
            'due_date': DateInput(attrs={'class': 'form-control'}),
        }

class ProjectForm(ModelForm):

    class Meta:
        model = Project
        fields = ['title', 'description']
        widgets = {
            'title': TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Project title'}),
            'description': Textarea(attrs={'class': 'form-control', 'placeholder': 'Enter description'}),
        }

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.contrib.auth import login
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Project, Task, User
from .forms import CommentForm, TaskForm, ProjectForm

class ProjectCreate(LoginRequiredMixin, CreateView):
  model = Project
  form_class = ProjectForm

  def form_valid(self, form):
    form.instance.user = self.request.user
    return super().form_valid(form)

class ProjectUpdate(LoginRequiredMixin, UpdateView):
  model = Project
  form_class = ProjectForm


class ProjectDelete(LoginRequiredMixin, DeleteView):
  model = Project
  success_url = '/projects'

@login_required
def add_comment(request, project_id):
  form = CommentForm(request.POST)
  if form.is_valid():
    new_comment = form.save(commit=False)
    new_comment.project_id = project_id
    new_comment.user = request.user
    new_comment.save()
  return redirect('detail', project_id=project_id)


class TaskCreate(LoginRequiredMixin, CreateView):
  model = Task
  form_class = TaskForm

  def form_valid(self, form):
    form.instance.project_id = self.kwargs['project_id']
    return super().form_valid(form)
    


class TaskUpdate(LoginRequiredMixin, UpdateView):
  model = Task
  form_class = TaskForm

class TaskDelete(LoginRequiredMixin, DeleteView):
  model = Task
  def get_success_url(self):
      return reverse(
          'detail',
          kwargs={
              'project_id': self.object.project.id,
          }
      )

def home(request):
    return render(request, 'home.html')

@login_required
def projects_index(request):
  projects = Project.objects.filter(user=request.user)
  assoc_projects = Project.objects.filter(members=request.user)
  return render(request, 'projects/index.html', {
    'projects': projects,
    'assoc_projects' : assoc_projects
  })

@login_required
def projects_detail(request, project_id):
  project = Project.objects.get(id=project_id)
  tasks = project.task_set.all()
  id_list = project.members.all().values_list('id')
  members_not_assoc = User.objects.exclude(id__in=id_list).exclude(id=project.user.id)
  comment_form = CommentForm()
  return render(request, 'projects/detail.html', {
    'project': project,
    'tasks' : tasks,
    'members': members_not_assoc,
    'comment_form' : comment_form
  })

@login_required
def tasks_detail(request, project_id, task_id):
  project = Project.objects.get(id=project_id)
  task = Task.objects.get(id=task_id)
  return render(request, 'tasks/detail.html', {
    'project': project,
    'task' : task
  })

def assoc_member(request, project_id, member_id):
  Project.objects.get(id=project_id).members.add(member_id)
  return redirect('detail', project_id=project_id)

def unassoc_member(request, project_id, member_id):
  Project.objects.get(id=project_id).members.remove(member_id)
  return redirect('detail', project_id=project_id)

def signup(request):
  error_message = ''
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('index')
    else:
      error_message = 'Invalid sign up - try again'
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poiret+One&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Comfortaa&display=swap" rel="stylesheet">
    <link href='https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css' rel='stylesheet'>
    <link rel="icon" type="image/x-icon" href="{% static 'images/wand.png' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <title>Workflow Wiz</title>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" id="navbar">
        <div class="container-fluid">
            <a class="navlink" href="{% url 'home' %}">
                <div class="brand">
                    <img id="logo" class="d-inline-block align-center" src="/static/images/logo.png" width="60" height="50">
                    <h3 class="ww">WW</h3>
                </div>
            </a>
            {% if user.is_authenticated %}
                <a class="navlink" href="{% url 'home' %}">Home</a>
                <a class="navlink" href="{% url 'projects_create' %}">Create Project</a>
                <a class="navlink" href="{% url 'index' %}">My Projects</a>
                <a class="navlink btn btn-primary" href="{% url 'logout' %}">Log Out</a>
            {% else %}
            <div>
                <a class="btn btn-primary" href="{% url 'signup' %}">Sign Up</a>
                <a class="navlink btn btn-primary" href="{% url 'login' %}">Log In</a>
            </div>
            {% endif %}
        </div>
    </nav>
    <main class="container">
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-md-6" id="home-content">
            <h1> Welcome to Workflow Wiz</h1>
            <h4 class="mt-3">You can manage your project's and teammates all in one location!
                <img src="static/images/wand.png" alt="">
            </h4>
            <a class="btn btn-primary" href="{% url 'signup' %}">Sign Up Now!</a>
        </div>
        <div class="col-md-6" id="home-img">
                <img src="static/images/landing.png">
        </div>
    </div>
    
{% endblock %}

main_app/templates/main_app/project_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Project</h1>

  <h4>Are you sure you want to delete "{{ object.title }}"?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn btn-primary">
    <a href="{% url 'detail' project.id %}" class="btn btn-primary">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/project_form.html
{% extends 'base.html' %}

{% block content %}

{% if object %}
    <h1>Edit <span>{{ object.title }}</span></h1>
{% else %}
    <h1>Create</h1>
{% endif %}

<form action="" method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!">
</form>

{% endblock %}

main_app/templates/main_app/task_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Task</h1>

  <h4>Are you sure you want to delete {{ object.title }}?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn btn-primary">
    <a href="{% url 'detail' object.project.id %}" class="btn btn-primary">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/task_form.html
{% extends 'base.html' %}

{% block content %}

{% if object %}
    <h1>Edit <span>{{ object.title }}</span></h1>
{% else %}
    <h1>Create</h1>
{% endif %}

<form action="" method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!">
</form>


{% endblock %}

main_app/templates/projects/detail.html
{% extends 'base.html' %}
{% block content %}

<h1 class="text-center">{{ project.title }} Project Details</h1>

<div class="container" id="project-container">
  <div class="row">
    <div class="col-4 mt-3 mb-3">
      <div class="card" id="project-detail-card">
        <div class="card-content">
          <span class="card-title" id="project-title">{{ project.title }}</span>
          <p class="mt-1">{{ project.description|linebreaks }}</p>
          {% if project.completion %}
            <p>Completed</p>
          {% else %}
            <p>In Progress</p>
          {% endif %}
        </div>
        {% if request.user == project.user %}
        <div class="card-action" id="project-buttons">
          <a href="{% url 'projects_update' project.id %}" class="btn btn-primary" id="edit-project">Edit</a> 
          <a href="{% url 'projects_delete' project.id %}" class="btn btn-primary">Delete</a> 
        </div>
        {% endif %}
      </div>
    </div>
    <div class="col-4 mt-3 mb-3">
      <div class="card">
        <form class="text-center mb-2 mt-1" action="{% url 'tasks_create' project.id %}" method="POST">
          <button type="submit" class="btn btn-primary"> Add Task </button>
          {% csrf_token %}
        </form>
        <div class="card">
          {% for task in project.task_set.all %}
              <a href="{% url 'tasks_detail' project.id task.id %}" id="task-title" style=>
                <div class="card-header pb-0 d-flex justify-content-between">{{ task.title }}</a>
                  {% if task.completion == False %}
                  In Progress
                  {% endif %}
                </div>
              <div class="card-body pb-0 pt-2 mb-0">
                <p>Assigned to: {{ task.assignee }}</p>
                {% if task.completion == True %}
                <div class="form-check form-check-inline">
                  <input class="form-check-input" type="checkbox" value="True" checked>
                  <label class="form-check-label" for="inlineCheckbox1">Completed</label>
                </div>
                {% endif %}
              </div>
          {% empty %}
            <div class="card-panel teal-text center-align">No Tasks Yet</div>
          {% endfor %}
        </div>
      </div>
    </div>
    <div class="col-4 mt-3 mb-3">
      <div class="card">
          <div class="card-content">
            <span class="card-title">
              <h3 class="text-center">Comment Section</h3>
            </span>
            <form action="{% url 'add_comment' project.id %}" method="POST">
              {% csrf_token %}
              <div class="comment-head">
                {{ comment_form.as_p }}
              </div>
              <input type="submit" class="btn btn-primary btn-sm" value="Add Comment" id="add-comment">
            </form>
            <div class="comment-container">
                {% for comment in project.comment_set.all %}
                  <p id="comments">
                    <h5 id="userc">{{comment.user.username}} :</h5>
                    {{comment.comment}}
                  </p>
                {% endfor %}
              </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<h3>Available Members</h3>
<div class="container-lg">
  <div class="row">
    {% if members.count %}
    {% for member in members.all %}
    <div class="card col-sm-2 text-center" id="members">
      <div class="card-content">
        <span class="card-title">
          {{ member }}
        </span>
      </div>
      <div class="card-action mb-1">
        <form action="{% url 'assoc_member' project.id member.id %}" method="POST">
          {% csrf_token %}
          <button type="submit" class="btn btn-primary btn-sm" id="add-members">Add</button>
        </form>
      </div>
    </div>
    {% endfor %}
    {% else %}
      <h5>{{project.title}} Already Has All members Available</h5>
    {% endif %}
  </div>
</div>



{% endblock %}

main_app/templates/projects/index.html
{% extends 'base.html' %}
{% block content %}

<h1 class="text-center mt-3 mb-3">My Projects</h1>
<div class="container" id="project-index">
    <div class="row">
        {% for project in projects %}
        <div class="col-sm-4 mb-3 mt-3">
            <div class="card">
                <h3 class="card-title text-center">{{ project.title }}</h3>
                <p class="card-text">Description: {{ project.description }}</p>
                <a href="{% url 'detail' project.id %}" class="btn btn-primary">View Project</a>
            </div>
        </div>
        {% empty %}
        <div class="card">
            <h1>No projects yet, <br> would you like to get started?
                <a class="btn btn-primary" href="{% url 'projects_create' %}">Create A Project</a>
            </h1>
        </div>
        {% endfor %}
    </div>
</div>

<h1 class="text-center mb-3">Associated Projects</h1>
<div class="container" id="project-index2"> 
    <div class="row">
        {% for project in assoc_projects %}
        <div class="col-sm-4 mb-3 mt-3">
            <div class="card">
                <h3 class="card-title text-center">{{ project.title }}</h3>
                <p class="card-text">Description: {{ project.description }}</p>
                <a href="{% url 'detail' project.id %}" class="btn btn-primary">View Project</a>
            </div>
        </div>
        {% empty %}
        <div class="card">
            <h1>You have not been added to any projects.</h1>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

main_app/templates/tasks/detail.html
{%  extends 'base.html' %}

{% block content %}

<h1 class="text-center">{{ task.title }}</h1>
<div class="card justify-content-center">
<div>
    <div class="card-header">{{ task.title }}</div>
        <div class="card-body pb-0 pt-2 mb-0">
          <p>Description: {{ task.description }}</p>
        </div>
        <div class="card-body pb-0 pt-2 mb-0">
            Priority: {{ task.get_priority_display }}
        </div>
        <div class="card-body pb-0 pt-2 mb-0">
            Due Date: {{ task.due_date }}
        </div>
        {% if task.completion == True %}
        <div class="form-check pt-2" id="completed">
          <input class="form-check-input pl-2" type="checkbox" value="True" checked>
          <label class="form-check-label" for="inlineCheckbox1">Completed</label>
        </div>
        {% else %}
          <p id="working">Still Working...</p>
        {% endif %} 
      </div>
  </div>
<div class="d-flex flex-row-reverse mt-2">
  <a class="btn btn-primary" href="{% url 'tasks_update' project.id task.id %}">EDIT</a>
  <a class="btn btn-primary" id="middle-button" href="{% url 'detail' project.id %}">BACK</a>
  <a class="btn btn-primary" href="{% url 'tasks_delete' project.id task.id %}">DELETE</a>
</div>
{% endblock %}